force-app/main/default/objects/Api__mdt/Api__mdt.object-meta.xml
<CustomObject>
    <label>Api</label>
    <pluralLabel>Apis</pluralLabel>
</CustomObject>

force-app/main/default/objects/Api__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <businessOwnerGroup>CRM</businessOwnerGroup>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Api__mdt/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <businessOwnerGroup>CRM</businessOwnerGroup>
    <description>This is the encrypted key for the api.</description>
    <inlineHelpText>DO NOT MODIFY</inlineHelpText>
    <label>Key</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Api__mdt/fields/Keychain__c.field-meta.xml
<CustomField>
    <fullName>Keychain__c</fullName>
    <businessOwnerGroup>CRM</businessOwnerGroup>
    <inlineHelpText>DO NOT MODIFY</inlineHelpText>
    <label>Keychain</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Key__mdt/Key__mdt.object-meta.xml
<CustomObject>
    <description>Encryption Keys</description>
    <label>Key</label>
    <pluralLabel>Keys</pluralLabel>
</CustomObject>

force-app/main/default/objects/Key__mdt/fields/Encryption_Key__c.field-meta.xml
<CustomField>
    <fullName>Encryption_Key__c</fullName>
    <businessOwnerGroup>CRM</businessOwnerGroup>
    <description>This is the encryption key for an api.</description>
    <inlineHelpText>DO NOT MODIFY</inlineHelpText>
    <label>Encryption Key</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Key__mdt/fields/Keychain__c.field-meta.xml
<CustomField>
    <fullName>Keychain__c</fullName>
    <businessOwnerGroup>CRM</businessOwnerGroup>
    <description>This connects to a record in the api list</description>
    <inlineHelpText>DO NOT MODIFY</inlineHelpText>
    <label>Keychain</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Sample_API_Settings__c/Sample_API_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for Boomi API</description>
    <label>Boomi API Settings</label>
</CustomObject>

force-app/main/default/objects/Sample_API_Settings__c/fields/Is_Live_Environment__c.field-meta.xml
<CustomField>
        <fullName>Is_Live_Environment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If true calls production apis.</description>
        <inlineHelpText>If true calls production apis.</inlineHelpText>
        <label>Is Live Environment</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Sample_API_Settings__c/fields/Production_Endpoint__c.field-meta.xml
<CustomField>
        <fullName>Production_Endpoint__c</fullName>
        <label>Production Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Sample_API_Settings__c/fields/Production_Key__c.field-meta.xml
<CustomField>
        <fullName>Production_Key__c</fullName>
        <description>Authorization for Production.</description>
        <inlineHelpText>Authorization for Production.</inlineHelpText>
        <label>Production Key</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Sample_API_Settings__c/fields/Test_Endpoint__c.field-meta.xml
<CustomField>
        <fullName>Test_Endpoint__c</fullName>
        <label>Test Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Sample_API_Settings__c/fields/Test_Key__c.field-meta.xml
<CustomField>
    <fullName>Test_Key__c</fullName>
    <description>Authorization for Test.</description>
    <inlineHelpText>Authorization for Test.</inlineHelpText>
    <label>Test Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SampleAPIProxy.cls
/**
 * @description proxy provide auth details to call a sample API
 * @author M Rainboldt
 * @created NOV 2022
 */
public with sharing class SampleAPIProxy {
    public String authType {get; private set;}
    public String endpoint {get; private set;}

    private Api__mdt apiSettings;
	private Key__mdt keySettings;

    public String authToken{
        get{
            return EncodingUtil.base64Decode(Helper.decrypt(apiSettings.Key__c, keySettings.Encryption_Key__c, apiSettings.Keychain__c)).toString();
        }
        private set;
    }

	/**
	 * @description initialize the settings
	 */
	private void getSettings(String environment)
	{
		apiSettings = [SELECT Key__c
						, Keychain__c
						, Endpoint__c 
						FROM Api__mdt 
						WHERE DeveloperName = :environment
						LIMIT 1];
		keySettings = [SELECT Encryption_Key__c
						FROM Key__mdt
						WHERE Keychain__c = :apiSettings.Keychain__c
						LIMIT 1];
		
	}

    public SampleAPIProxy() {
        Sample_API_Settings__c settings = Sample_API_Settings__c.getInstance(UserInfo.getUserId());
        this.authType = 'Basic';
        //this setting tells us to call the live version of the test version of Stripe
        if(settings.Is_Live_Environment__c)
        {
            this.getSettings('API_Prod');
            //this.authToken = settings.Production_Key__c;
        	this.endpoint = settings.Production_Endpoint__c;
        }
        else
        {
            this.getSettings('API_Test');
            //this.authToken = settings.Test_Key__c;
        	this.endpoint = settings.Test_Endpoint__c;
        }
    }

    public class SampleApiProxyException extends Exception{}
}